---
title: "IntermediaiRe"
---

This is the companion website for the class "IntermediaiRe"[^1]. You will find here the objectives, schedule, slides, and other materials related to this course.

# Objectives

The objective of this class is to show students how to combine their skills in R programming to create reproducible reports with R Markdown, along with publication ready figures. The course ends with a workshop during which students will be asked to work in teams on a dataset extracted from a recent publication, reproduce some or all the figures from the paper, and propose alternative visualizations.

# Schedule
 
Morning = 9h30 to noonish. Afternoon = noonish+1h to 17h30. 

 * Day 1: advanced reporting with R Markdown
 * Day 2: visualization
 * Day 3: group project

During this class, we will work on a shared script ([link]({{< meta shared_script_url >}})).

# To go further

  * [Advanced R programming](https://adv-r.hadley.nz/index.html) 
  * [Introduction to R Markdown](https://rmarkdown.rstudio.com/articles_intro.html)
  * [from Data to Viz](https://www.data-to-viz.com/)
  * [Quarto](https://quarto.org/)
  * [Tidyverse Style Guide](https://style.tidyverse.org/)
  * [Our beginner level course](https://vguillemot.github.io/debuter/) (in R)


[^1]: have you spotted this infinitely funny pun that works only in French?